language: python

python:
  - "3.6.6"

services:
  - mongodb

before_script:
  - "mongo lcs-db --eval 'db.createUser({user: \"creep\", pwd: \"@radiohead.ed\", roles: [\"readWrite\"]});'"
  - cp config.travis.py config.py

install:
  - pip install -r requirements.txt

script:
  - python -m pylint *.py && python -m pytest --cov=.
